# Numpy:

NumPy stands for Numerical Python.
NumPy is a Python library used for working with arrays. 
It also has functions for working in domain of linear algebra,matrices.
NumPy was created in 2005 by Travis Oliphant. 
It is an open source project and you can use it freely. 

Import it first

In [120]:
import numpy as np

#here np is the alias

Create an array

In [4]:
#1D array
arr1=np.array([1,2,3])
arr1

array([1, 2, 3])

In [6]:
arr1=np.array(["m","o","h"])
arr1

array(['m', 'o', 'h'], dtype='<U1')

Unlike the range function in python here we have arange function

In [7]:
arr1=np.arange(0,19)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [9]:
#with stepcount
arr1=np.arange(0,19,2)
arr1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

2D arrays

In [11]:
arr1=np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

# Arthmetic Operations on arrays

In [13]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

In [14]:
arr1+arr2

array([5, 7, 9])

In [15]:
arr1-arr2

array([-3, -3, -3])

In [16]:
arr1*arr2

array([ 4, 10, 18])

In [17]:
arr1/arr2

array([0.25, 0.4 , 0.5 ])

In [18]:
arr1%arr2

array([1, 2, 3], dtype=int32)

# Trignometric Operations on arrays

In [19]:
arr1

array([1, 2, 3])

In [20]:
np.log(arr1)

array([0.        , 0.69314718, 1.09861229])

In [21]:
np.sin(arr1)

array([0.84147098, 0.90929743, 0.14112001])

In [22]:
np.tan(arr1)

array([ 1.55740772, -2.18503986, -0.14254654])

In [23]:
np.cos(arr1)

array([ 0.54030231, -0.41614684, -0.9899925 ])

# Indexing

In [27]:
arr=np.arange(0,10)

In [28]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr[0] #getting first element as indexing starts from 0

0

In [30]:
arr[::-1]  #reverse array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [31]:
arr[-1] #last element

9

# Slicing

In [ ]:
arr=np.array([1, 2, 3, 4, 5, 6, 7])

In [36]:
arr[1:5] #Slice elements from index 1 to index 5 (start:end)

array([2, 3, 4, 5])

In [33]:
arr[4:]            #Slice elements from index 4 to the end of the array:

array([5, 6, 7])

In [34]:
arr[:-3:-1]         #Slice from the index 3 from the end to index 1 from the end:

array([7, 6])

In [35]:
arr[1:5:2]           #Slice very other element from index 1 to index 5 #use steparr

array([2, 4])

# Data Types in Python
By default Python have these data types:

In [ ]:
strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
integer - used to represent integer numbers. e.g. -1, -2, -3
float - used to represent real numbers. e.g. 1.2, 42.42
boolean - used to represent True or False.
complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

# Data Types in NumPy
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.



Below is a list of all data types in NumPy and the characters used to represent them.
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
M - datetime
O - object
S - string


checking dtypes of arrays 

In [39]:
arr=np.array([1,2,4])
arr.dtype

dtype('int32')

In [40]:
arr=np.array([1.2,2.2,4.2])
arr.dtype

dtype('float64')

In [44]:
arr=np.array(["banana","orange","apple"])
arr

array(['banana', 'orange', 'apple'], dtype='<U6')

The Difference Between Copy and View

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [45]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

#change not made to copy array


[42  2  3  4  5]
[1 2 3 4 5]


In [47]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

#using view change is made

[42  2  3  4  5]
[42  2  3  4  5]


# Shape of an Array



The shape of an array is the number of elements in each dimension.


In [48]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)  #2 rows 4 cols

(2, 4)


# Reshaping arrays


Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.



In [49]:
#convert 1d to 2d ie change dimensions
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
newarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [51]:
#convert 1d to 3d
newarr = arr.reshape(2, 3, 2)
newarr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

# Iterating On arrays

In [ ]:
#simple! use for loop

In [52]:
arr1

array([1, 2, 3])

In [53]:
for i in arr1:
    print(i)

1
2
3


# Joining (Concat) arrays

In [ ]:
print(arr1)
print(arr2)

In [63]:
arr3=np.concatenate([arr1,arr2])
arr3

array([1, 2, 3, 4, 5, 6])

# Split arrays (opposite of join)

In [64]:
arr3

array([1, 2, 3, 4, 5, 6])

In [71]:
np.array_split(arr3,2)


[array([1, 2, 3]), array([4, 5, 6])]

# Searching Arrays #where

In [72]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [76]:
#getting index of arrays where array(values) match
arr1=np.array([1,2,3,4])
arr2=np.array([5,2,7,4])
np.where(arr1==arr2)

(array([1, 3], dtype=int64),)

# Sorting arrays

In [78]:
arr=np.array([1,5,8,964,246])
arr.sort()

In [79]:
arr   #ascending order

array([  1,   5,   8, 246, 964])

In [99]:
arr=np.array([1,5,8,964,246])
sorted(arr,reverse=True)  #descending order

[964, 246, 8, 5, 1]

# Random numbers in array

In [100]:
from numpy import random

x = random.randint(100)
print(x)

89


In [ ]:
x=random.randint(100,size=(5)) #5 random nos
print(x)

In [114]:
x=np.random.randn(10)  #n means -ve and +ve equal
print(x)

[ 2.05228829 -1.56691815 -0.8696092  -0.80231244  1.0849907  -0.44160961
 -0.44106573 -1.45887234 -1.17087166  1.16827845]


In [109]:
x = random.rand() #between 0 to 1
print(x)

0.028221357117879875


In [110]:
x = random.rand(5)
print(x)

[0.42194054 0.19234506 0.05405905 0.05225582 0.73268712]


#Equal spaces between data points

In [118]:
np.linspace(0,5) #default 0.1

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [119]:
np.linspace(0,5,10)  #10 equal spaces

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

# Stacking (combining)

In [121]:
a=[[1,2],[3,4]]
b=[[5,6],[7,8]]

In [127]:
np.stack([a,b])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [131]:
#vstack #hstack #depth stack
print(np.hstack([a,b]))

print(np.vstack([a,b]))


[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [132]:
print(np.dstack([a,b]))


[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


# Splitting (opposite of stacking)

In [137]:
#possibleon 1d array
d=np.array([1,2,3,4])
np.split(d,2,axis=0)

[array([1, 2]), array([3, 4])]

In [139]:
a=np.array(a)
np.split(a,2,axis=0) #1

[array([[1, 2]]), array([[3, 4]])]

In [ ]:
#dsplit #3d array

# Good to Go!!You know numpy now :)